//
// Created by Tom on 2026/3/13.
//

#ifndef SHMIPCC_SHMSERVERCONFIG_H
#define SHMIPCC_SHMSERVERCONFIG_H

#define SHM_SERVER_MAX_UDS_PROTOCOL_FD 10
#define SHM_SERVER_MAX_PROGRESS_COUNT 2
#define SHM_SERVER_PROTOCOL_HEAD_SIZE 7

#define SHM_SERVER_DEFAULT_NAME "shmIpc"

#define SHM_META_DATA_DEFAULT_SHARE_MEMORY_SIZE 16 * 1024 * 1024 //16MB
#define SHM_META_DATA_SLICE_SIZE 16 * 1024 // 16KB
#define SHM_META_DATA_EVENT_QUEUE_SIZE 10
#define SHM_META_DATA_INVALID_SLICE_INDEX 0xFFFFFFFF

#endif //SHMIPCC_SHMSERVERCONFIG_H
